apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-cronjob-container
            image: nginx
            command: ["/bin/sh", "-c"]
            args: ["date; echo Hello from CronJob"]
          restartPolicy: OnFailure
